apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        update-timestamp: "{{ .Values.timestamp }}"
    spec:
      containers:
        - name: my-app-container 
          image: vijaysakhare709/myfirstworkflow:latest
          ports:
            - containerPort: 8080
