name: myfirstworkflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' 
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build With Maven JAVA Base Application
        run: mvn clean install 
        
      - name: Chack The Artifacts In Target Folder Uing Ls Command
        run: ls target  
        
      - name: Change Name Of Student Application
        run: mv target/studentapp-2.2-SNAPSHOT.war target/student.war
        
      - name: After Change The Name Of Artifacts In Target Folder Uing Ls Command
        run: ls target 
        
      - name: login To Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Creating Docker images 
        run: |
          cat << EOF > dockerfile
          FROM tomcat
          COPY target/student.war ./webapps/
          EOF
      - name: Chack Docker File   
        run: |
          ls
          cat dockerfile
          
      - name: Set JOB_NAME environment variable
        run: echo "JOB_NAME=${{ github.workflow }}" >> $GITHUB_ENV
        
      - name: Set commit number as environment variable
        run: echo "COMMIT_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        
      - name: Set version For Docker Images
        id: set-version
        run: echo "::set-output name=version::v1.${{ env.COMMIT_NUMBER }}"
        
      - name: Build Docker Image And Tags Also
        run: |
          docker images ls
          docker --version
          docker image build -t  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} .
          docker image tag  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} vijaysakhare709/${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }}
          docker image tag  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} vijaysakhare709/${{ env.JOB_NAME }}:latest
          docker image ls
          
      - name: Push Docker Image To Docker Hub Repository And Chack 
        run: |
          docker image push vijaysakhare709/${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }}
          docker image push vijaysakhare709/${{ env.JOB_NAME }}:latest
          docker image ls
          
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
             # Empty script
             
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: See Azure Subscription Account Information
        run: |
          az account show
          
      - name: Set up AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: projectAresourcegroupA
          cluster-name: Vijay-kuberntes-cluster

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f servicelb.yaml
          # kubectl delete -f deployment.yaml
          # kubectl delete -f servicelb.yaml
          kubectl get service
          kubectl get pod
          kubectl get pods --all-namespaces 
          kubectl get service
