name: MyfirstWorkflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install 
    
      - name: pwd command
        run: pwd
        
      - name: ls command
        run: ls
        
      - name: ls target show
        run: ls target  
        
      - name: change name of student application
        run: mv target/studentapp-2.2-SNAPSHOT.war target/student.war
        
      - name: again ls
        run: ls target 
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: docker create images 
        run: |
          cat << EOF > dockerfile
          FROM tomcat
          COPY target/student.war ./webapps/
          EOF
      - name: chack docker file   
        run: |
          ls
          cat dockerfile
      - name: docker build
        run: |
          docker images ls
          docker --version
          docker image build -t  ${{ env.JOB_NAME }}${{ github.run_id }} .
          docker image tag  ${{ env.JOB_NAME }}${{ github.run_id }} vijaysakhare709/${{ env.JOB_NAME }}${{ github.run_id }}
          docker image tag  ${{ env.JOB_NAME }}${{ github.run_id }} vijaysakhare709/${{ env.JOB_NAME }}${{ github.run_id }}:latest
