name: myfirstworkflow
on: [push, workflow_dispatch]
permissions:
      id-token: write
      contents: read
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install 
    
      - name: pwd command
        run: pwd
        
      - name: ls command
        run: ls
        
      - name: ls target show
        run: ls target  
        
      - name: change name of student application
        run: mv target/studentapp-2.2-SNAPSHOT.war target/student.war
        
      - name: again ls
        run: ls target 
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: docker create images 
        run: |
          cat << EOF > dockerfile
          FROM tomcat
          COPY target/student.war ./webapps/
          EOF
      - name: chack docker file   
        run: |
          ls
          cat dockerfile
      - name: Set JOB_NAME
        run: echo "JOB_NAME=${{ github.workflow }}" >> $GITHUB_ENV
      - name: Set version
        id: set-version
        run: echo "::set-output name=version::v1.${{ github.run_id }}"
      - name: docker build
        run: |
          docker images ls
          docker --version
          docker image build -t  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} .
          docker image tag  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} vijaysakhare709/${{ env.JOB_NAME }}:hellostudent
          docker image tag  ${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }} vijaysakhare709/${{ env.JOB_NAME }}:latest
          docker image ls
      - name: push image to docker hub
        run: |
          docker image push vijaysakhare709/${{ env.JOB_NAME }}:${{ steps.set-version.outputs.version }}
          docker image push vijaysakhare709/${{ env.JOB_NAME }}:latest
          sudo docker image ls
          
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
             # Empty script
      - name: as ls
        run: az 
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: |
          az account show
          echo ${{ github.sha }}
          
      - name: Set up AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: projectAresourcegroupA
          cluster-name: Vijay-kuberntes-cluster

      - name: Deploy to AKS
        run: |
          docker pull vijaysakhare709/myfirstworkflow:latest
          kubectl apply -f deployment.yaml
          kubectl apply -f servicelb.yaml
          kubectl get service
          kubectl get pod
          kubectl get pods --all-namespaces
          kubectl get service
