name: MyfirstWorkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install 
    
      - name: pwd command
        run: pwd
        
      - name: ls command
        run: ls
        
      - name: ls target show
        run: ls target  
        
      - name: change name of student application
        run: mv target/studentapp-2.2-SNAPSHOT.war target/student.war
        
      - name: again ls
        run: ls target 
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install 
    
      - name: pwd command
        run: pwd
        
      - name: ls command
        run: ls
        
      - name: ls target show
        run: ls target  
        
      - name: change name of student application
        run: mv target/studentapp-2.2-SNAPSHOT.war target/student.war
        
      - name: again ls
        run: ls target 
